---
roles:
  - src: spirkaa.nano
  - src: spirkaa.zsh_prezto
  - src: geerlingguy.pip
  - src: geerlingguy.docker
collections:
  - name: ansible.posix
    version: 1.3.0
  - name: community.docker
    version: 2.3.0
  - name: community.general
    version: 4.7.0
  - name: community.network
    version: 3.1.0
